from app.mock_data import MQ_ONE, MQ_THREE, MQ_TWO

# `ssn` is stored raw here on purpose; the service masks it before it leaves the API.
INSURANCE: dict[str, dict] = {
    MQ_ONE: {
        "coverage": {
            "payer_name": "Medicare",
            "plan": "Medicare Part B",
            "member_id": "1EG4-TE5-MK72",
            "group_number": "N/A",
            "effective_date": "2026-01-01",
            "expiry_date": "2026-12-31",
        },
        "prior_authorization": {
            "auth_number": None,
            "service": "In-Center Hemodialysis",
            "status": "Pending",
            "valid_from": None,
            "valid_to": None,
        },
        "questionnaire": {
            "us_citizen": True,
            "veteran_eligible_for_va_benefits": True,
            "household_size": 3,
            "annual_income": 100,
            "marital_status": "Single",
            "state_of_residence": "Arkansas",
            "years_in_current_state": 3,
            "years_worked_and_paid_us_taxes": 10,
            "coverage_application_submitted": "2026-09-21",
            "pending_application_last_90_days": True,
            "can_provide_proof_of_state_residency": True,
            "incarcerated_or_in_halfway_house": True,
            "itin": "12121",
            "ssn": "192983",
        },
    },
    MQ_TWO: {
        "coverage": {
            "payer_name": "Blue Cross Blue Shield",
            "plan": "BCBS PPO Gold",
            "member_id": "XJH884120557",
            "group_number": "GRP-40211",
            "effective_date": "2026-01-01",
            "expiry_date": "2027-12-31",
        },
        "prior_authorization": {
            "auth_number": "PA-2026-118834",
            "service": "Home Hemodialysis",
            "status": "Approved",
            "valid_from": "2026-09-01",
            "valid_to": "2027-02-28",
        },
        "questionnaire": {
            "us_citizen": True,
            "veteran_eligible_for_va_benefits": False,
            "household_size": 2,
            "annual_income": 68000,
            "marital_status": "Married",
            "state_of_residence": "Colorado",
            "years_in_current_state": 22,
            "years_worked_and_paid_us_taxes": 35,
            "coverage_application_submitted": None,
            "pending_application_last_90_days": False,
            "can_provide_proof_of_state_residency": True,
            "incarcerated_or_in_halfway_house": False,
            "itin": None,
            "ssn": "521447306",
        },
    },
    MQ_THREE: {
        "coverage": {
            "payer_name": "Arkansas Medicaid",
            "plan": "ARHOME",
            "member_id": "AR7730014592",
            "group_number": "ARM-001",
            "effective_date": "2025-07-01",
            "expiry_date": "2026-10-31",
        },
        "prior_authorization": {
            "auth_number": "PA-2026-120417",
            "service": "Peritoneal Dialysis",
            "status": "Denied",
            "valid_from": None,
            "valid_to": None,
        },
        "questionnaire": {
            "us_citizen": True,
            "veteran_eligible_for_va_benefits": False,
            "household_size": 4,
            "annual_income": 24500,
            "marital_status": "Divorced",
            "state_of_residence": "Arkansas",
            "years_in_current_state": 12,
            "years_worked_and_paid_us_taxes": 18,
            "coverage_application_submitted": "2026-08-30",
            "pending_application_last_90_days": True,
            "can_provide_proof_of_state_residency": False,
            "incarcerated_or_in_halfway_house": False,
            "itin": None,
            "ssn": None,
        },
    },
}
